### ISSUE TITLE
[FE]CSS 변경 리펙토링, Mock서버 변경, storyBook 도입 

### ISSUE THREAD

**Issue by limshyun** [MeetYourBook/meet-your-book#14]
**제안하는 기능이 어떤 문제와 관련이 있나요? 설명해 주세요.**
- 가독성과 동적 스타일링은 Tailwind CSS가 적합하지 않습니다. 
- Mock서버로 json-server를 사용하고 있는데 json-server는 쿼리 파싱 커스텀이 불가능합니다.
- 테스트 코드를 작성하고자 하는데 Vitest로 확인하는 테스트는 컴포넌트가 제대로 렌더링되는지 콘솔에서 밖에 확인하지 못합니다.

**원하는 해결책을 설명해 주세요**
- 스타일 가독성을 향상시키고 상태에 따른 동적 스타일링 커스텀을 하고 싶습니다.
- 개발 속도를 향상하기 위해 Mock 서버를 쿼리 커스텀이 가능한 대체 라이브러리로 변경하고 싶습니다.
- hook과 같은 로직은 Vitest로 테스트하고, 컴포넌트가 어떻게 동작하는지, 어떻게 보여지는지, 어떻게 사용될수 있는지는 storyBook으로 문서화 하려 합니다.

**고려한 대안을 설명해 주세요**
 - Tailwind -> styled-component로 변경
 - json-server -> MSW(Mock Sevice Worker)로 변경
 - storyBook 도입 

**추가 정보**
- storyBook은 아래 사진과 같이 해당 컴포넌트가 렌더링 되는지, 어떻게 동작하는지, 어떻게 보여지는지, 어떻게 사용될수 있는지는 storyBook으로 문서화 할 수 있습니다.
![storyBookEX_image](https://github.com/user-attachments/assets/25aeb1e2-6314-46a6-a3fc-4709fd251f51)

**Comment by hiidy** [comment]
tailwind에서  styled-component로 옮겼을 때 개선된 점을 wiki에 적어도 좋을 것 같아요. 
ex) cloc같은 tool을 이용해서 코드량이 얼마나 줄었는지 혹은 유지보수 측면에서 어떤 개선점이 있는지
