### ISSUE TITLE
[FE] mock API 개발을 위한 Query 예시 및 데이터 요청

### ISSUE THREAD

**Issue by limshyun** [MeetYourBook/meet-your-book#22]
**제안하는 기능이 어떤 문제와 관련이 있나요? 설명해 주세요.**
- mock API를 개발하려하는데 현재 백엔드에서 진행중인 쿼리 예시를 상황별로 알고 싶습니다.

**원하는 해결책을 설명해 주세요**
- 상황마다 쿼리 예시 요청
- 목 데이터 json 요청(많이 주세요.)

## 
1. 페이지 첫 진입 시 모든 책 데이터 요청 쿼리
2. 저자, 통합검색, 출판사, 제목 선택 시 쿼리가 어떻게 변경되는지
3. 여러 도서관을 선택하면 어떻게 쿼리가 합쳐 지는지

##
- 각 예시 쿼리를 댓글로 남겨주세요.

**Comment by keon0711** [comment]
1. 모든 책
'api/books'

2. 검색 조건에 따른 쿼리
'api/books?title={제목}'
'api/books?author={작가}'
'api/books?publisher={출판사}'
'api/books?title={제목}&author={작가}&publisher={출판사}'

3. 여러 도서관
2번 API에 libraries 쿼리 파라미터만 추가
검색할 도서관 ID를 쉼표를 기준으로 추가
도서관 ID는 숫자('Long')로 표기

제목 검색 + 도서관 필터링
'api/books?title={제목}&libraries={도서관 ID, 도서관 ID...}'
